name: podcast-editor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ffmpeg
  - numpy
  - scipy
  - pip
  - pip:
      - librosa
      - soundfile
      - click
      - InquirerPy
      - tqdm
      - rich
      - moviepy 