name: podcast-multicam-editor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - moviepy
  - numpy
  - pytorch
  - torchaudio
  - torchvision
  - pip
  - pip:
      - git+https://github.com/openai/whisper.git
