name: podcast-multicam-editor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - pip
  - tqdm
  - pip:
    - argparse  # Incluido en Python 3.11 pero listado para claridad